### ISSUE TITLE
Plugin doesn't display on Craftbeerpi4 plugins folder

### ISSUE THREAD

**Issue by SpadBoy** [PiBrewing/cbpi4-iSpindle#1]
Hi all, I'm currently in front of little issue. I followed instructions to install correctly some plugins but iSpindel plugin doesn't appear in my CBPI4 instance. 
Do you allready have same issue ?

Thx a lot

**Comment by avollkopf** [comment]
No. everything is running as expected -> https://openbrewing.gitbook.io/craftbeerpi4_support/master/troubleshooting

**Comment by SpadBoy** [comment]
Thx for your response Alexander, I followed all of your instructions. 
Only iSpindle plug-in doesn’t appear. 
When I write « cbpi plugins » I can see iSpindle into the list but in my plugins folder on Craftbeerpi 4 isn’t not here.

I deactived and I reactived but nothing.

I will continue my investing.

Have a good week end 

Clément 

Envoyé de mon iPhone

**Comment by avollkopf** [comment]
But the questions on the versions you are using and how you installed the plugin (e.g. pypi.org or github) are still open.

#5 of the troubleshooting is finally the most important point as it may show errors during startup when the system is trying to load the plugin.

Regards,
Alex
